# Generated by Django 6.0.1 on 2026-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.CharField(max_length=255),
        ),
    ]
