# Generated by Django 6.0.1 on 2026-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiorecord',
            old_name='transcipt',
            new_name='transcript',
        ),
    ]
