# Generated by Django 6.0.1 on 2026-06-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_audiorecord_user_alter_audiorecord_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.URLField(),
        ),
    ]
