# Generated by Django 6.0.1 on 2026-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
