# Generated by Django 6.0.1 on 2026-06-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_audiorecord_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
