# Generated by Django 6.0.1 on 2026-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_audiorecord_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airesult',
            name='key_points',
        ),
        migrations.AddField(
            model_name='airesult',
            name='action_items',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='airesult',
            name='important_names_dates',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='airesult',
            name='translation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
