name: Django tests

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Defining env here makes it available across ALL steps, including pip install and django boots
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GEMINI_API_KEY: "dummy_key_for_testing"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r backend/requirements.txt

      - name: Run python backend/manage.py test
        run: python backend/manage.py test